export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_SUCCESS = 'AUTH_USER';
export const AUTH_FAIL = 'AUTH_USER';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';

export const SPOTIFY_GET_TRACKS = 'SPOTIFY_GET_TRACKS';
export const SPOTIFY_GET_TRACKS_START = 'SPOTIFY_GET_TRACKS_START';
export const SPOTIFY_GET_TRACKS_SUSPENDED = 'SPOTIFY_GET_TRACKS_SUSPENDED';
export const SPOTIFY_GET_TRACKS_RESUMED = 'SPOTIFY_GET_TRACKS_RESUMED';
export const SPOTIFY_GET_TRACKS_FAIL = 'SPOTIFY_GET_TRACKS_FAIL';
export const SPOTIFY_GET_TRACKS_SUCCESS = 'SPOTIFY_GET_TRACKS_SUCCESS';
