export const FETCH_LIBRARY_TRACKS = 'FETCH_LIBRARY_TRACKS';
export const FETCH_PLAYLIST_TRACKS = 'FETCH_PLAYLIST_TRACKS';
export const FETCH_ARTIST_TOP_TRACKS = 'FETCH_ARTIST_TOP_TRACKS';
export const FETCH_RELATED_ARTISTS = 'FETCH_RELATED_ARTISTS';
export const ADD_TRACKS_TO_PLAYLIST = 'ADD_TRACKS_TO_PLAYLIST';

// LOOK_CLOSER = FETCH_PLAYLIST_TRACKS + FETCH_ARTIST_TOP_TRACKS + ADD_TRACKS_TO_PLAYLIST
// DIVE_DEEPER = FETCH_PLAYLIST_TRACKS + FETCH_RELATED_ARTISTS + FETCH_ARTIST_TOP_TRACKS + ADD_TRACKS_TO_PLAYLIST
